/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxyAssignedSol from "./ProxyAssigned.sol";
export * as proxyManualSol from "./ProxyManual.sol";
