/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Logic1Assigned } from "./Logic1Assigned";
export type { Logic2Assigned } from "./Logic2Assigned";
export type { ProxyAssigned } from "./ProxyAssigned";
