/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Logic1Assigned__factory } from "./Logic1Assigned__factory";
export { Logic2Assigned__factory } from "./Logic2Assigned__factory";
export { ProxyAssigned__factory } from "./ProxyAssigned__factory";
