/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxyAssignedSol from "./ProxyAssigned.sol";
export type { proxyAssignedSol };
import type * as proxyManualSol from "./ProxyManual.sol";
export type { proxyManualSol };
export * as factories from "./factories";
export type { Logic1Assigned } from "./ProxyAssigned.sol/Logic1Assigned";
export { Logic1Assigned__factory } from "./factories/ProxyAssigned.sol/Logic1Assigned__factory";
export type { Logic2Assigned } from "./ProxyAssigned.sol/Logic2Assigned";
export { Logic2Assigned__factory } from "./factories/ProxyAssigned.sol/Logic2Assigned__factory";
export type { ProxyAssigned } from "./ProxyAssigned.sol/ProxyAssigned";
export { ProxyAssigned__factory } from "./factories/ProxyAssigned.sol/ProxyAssigned__factory";
export type { Logic1Manual } from "./ProxyManual.sol/Logic1Manual";
export { Logic1Manual__factory } from "./factories/ProxyManual.sol/Logic1Manual__factory";
export type { Logic2Manual } from "./ProxyManual.sol/Logic2Manual";
export { Logic2Manual__factory } from "./factories/ProxyManual.sol/Logic2Manual__factory";
export type { ProxyManual } from "./ProxyManual.sol/ProxyManual";
export { ProxyManual__factory } from "./factories/ProxyManual.sol/ProxyManual__factory";
